- name: Updating MISP SQL config with remote SQL
  ansible.builtin.template:
    src: ../template/templates/database.php.j2
    dest: "{{ misp_rootdir }}/app/Config/database.php"
    mode: '0600'
    backup: yes
    owner: "{{ www_user }}"